# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://phyLearn.github.com
date_format: "ordinal"
title: 彭怀玉的个人博客
subtitle: “走一步，再走一步”
description: “彭怀玉的个人博客”
keywords: 彭怀玉, penghuaiyu
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
source_code: https://github.com/phyLearn/phyLearn.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: penghuaiyu
organization: Cyber, Inc.
organization_url: https://www.phyLearn.github.io
location: ChangSha,China
email: phyprivate@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: phyLearn
facebook_username: 彭怀玉
weibo_username: 信安Smile

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: phyLearn
disqus_username: phyLearn

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
